# Generated by Django 2.2.2 on 2019-07-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('bookingTime', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('notes', models.CharField(max_length=2000)),
            ],
        ),
    ]
