# Generated by Django 2.2.2 on 2019-07-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190723_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
