# Generated by Django 2.2.2 on 2019-07-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
    ]
