# Generated by Django 2.2.2 on 2019-07-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('start_month', models.IntegerField()),
                ('end_month', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='reservation_IDs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='advertising.Reservation'),
        ),
    ]
