# Generated by Django 2.2.2 on 2019-08-03 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_rating_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertising.Property'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
