# Generated by Django 2.2.2 on 2019-07-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_auto_20190713_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rating_IDs',
        ),
        migrations.RemoveField(
            model_name='property',
            name='reservation_IDs',
        ),
        migrations.AddField(
            model_name='rating',
            name='property',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertising.Property'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertising.Property'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(to='advertising.Feature'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_month',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_year',
            field=models.CharField(max_length=4),
        ),
    ]
