# Generated by Django 2.2.2 on 2019-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_auto_20190714_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
