# Generated by Django 2.2.2 on 2019-08-05 09:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0003_auto_20190803_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=None, size=None),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
