# Generated by Django 2.2.2 on 2019-07-23 02:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertising', '0004_auto_20190721_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='buildingType',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num_bathroom',
        ),
        migrations.RemoveField(
            model_name='property',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='property',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street',
        ),
        migrations.RemoveField(
            model_name='property',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='building_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=[], size=None),
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=['h', 't', 't', 'p', ':', '/', '/', 'w', 't', 'l', 'r', 'e', 'a', 'l', 't', 'y', '.', 'm', 'y', '/', 'a', 'd', 'm', 'i', 'n', '/', 'p', 'r', 'o', 'p', 'e', 'r', 't', 'y', '/', 'd', 'e', 'f', 'a', 'u', 'l', 't', '.', 'j', 'p', 'g'], size=None),
        ),
        migrations.AddField(
            model_name='property',
            name='num_bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='num_beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='num_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='from_dataset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='property_id',
            field=models.ForeignKey(default='11156', on_delete=django.db.models.deletion.CASCADE, to='advertising.Property'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='space',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='rating',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(default=5.0),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
