# Generated by Django 2.2.2 on 2019-07-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0005_rating_is_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='address',
        ),
    ]
