# Generated by Django 2.2.2 on 2019-07-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0006_auto_20190714_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.URLField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='post_code',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='suburb',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
