# Generated by Django 2.2.2 on 2019-07-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0007_auto_20190716_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='space',
            field=models.CharField(default=None, max_length=1500),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
