# Generated by Django 2.2.2 on 2019-07-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0008_auto_20190716_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.AddField(
            model_name='property',
            name='num_Room',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='num_bathroom',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='avg_Rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='num_Guests',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
