# Generated by Django 2.2.2 on 2019-07-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0009_auto_20190716_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prices',
            field=models.FloatField(),
        ),
    ]
