# Generated by Django 2.2.2 on 2019-07-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0010_auto_20190716_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='avg_Rating',
            new_name='avg_rating',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='num_Guests',
            new_name='num_guests',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='num_Room',
            new_name='num_room',
        ),
    ]
