# Generated by Django 2.2.2 on 2019-07-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0011_auto_20190716_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='images',
            new_name='image',
        ),
    ]
