# Generated by Django 2.2.2 on 2019-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0012_auto_20190716_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='num_room',
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='property',
            name='prices',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='suburb',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
