# Generated by Django 2.2.2 on 2019-08-05 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0005_booking_num_guests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertising', '0004_auto_20190805_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=2000)),
                ('from_dataset', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertising.Property')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
