# Generated by Django 2.2.2 on 2019-08-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='from_dataset',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='is_anonymous',
        ),
        migrations.AlterField(
            model_name='rating',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
